Fix glossary section
AY2324S1-CS2103T-T11-4/tp pull request #316
Opened 2023-11-08 15:28 UTC by WangCheng0116

2023-11-08 16:09 UTC, itsNatTan requested changes
Please add that clarification. Otherwise lgtm

2023-11-08 16:09 UTC, itsNatTan commented on docs/UserGuide.md
> +| **Level**                             | The level represents the proficiency with a specific flashcard.
Perhaps add a line saying lower means less proficient or smth to that effect

2023-11-08 16:12 UTC, WangCheng0116 commented on docs/UserGuide.md
> +| **Level**                             | The level represents the proficiency with a specific flashcard.
i have mentioned this in this [commit](https://github.com/AY2324S1-CS2103T-T11-4/tp/pull/316/commits/68f13cc3a2f5b4583f7d936c37aeed09c12e3270) but i guess you are right. It has been fixed.

2023-11-09 05:37 UTC, itsNatTan commented
Lgtm

2023-11-09 05:39 UTC, itsNatTan approved these changes
LGTM thanks for changing

2023-11-09 06:49 UTC, merged